source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'SocketClient' do
	pod 'CocoaAsyncSocket',:git=>'https://github.com/robbiehanson/CocoaAsyncSocket.git',:tag => '7.6.1'
end
